#!/usr/bin/env zsh

git config --get-regex 'autogitbundle\..*\.prefix' | cut -d ' ' -f2- | sort -u | xargs -I {} find {} -type f -name HEAD -execdir zsh -c '[[ -f config && -d objects ]] && autogitbundle' \;
