#!/usr/bin/env zsh

prefixes=()
for p in "${(u@)${(ps:\0:):-"$(git config --null --get-regex '^autogitbundle\..*\.prefix')"}#*$'\n'}"; do
	if [[ "${p:(-1)}" == "/" ]]; then
		p="${p%/}"
		prefixes+=( ${~:-"$p"} )
	else
		prefixes+=( ${~:-"${p}*/"} )
	fi
done
prefixes=( "${(u)prefixes[@]%/}" )
#TODO This approach has a problem where the same gitbundles will be generated multiple times if a repo is configured to generate multiple gitbundles where one prefix is a subfolder of another prefix.
find "${prefixes[@]}" -type f -name HEAD -execdir zsh -c '
	[[ -f config && -d objects ]] || exit
	cd "${"$(git config --get core.worktree)":-${PWD%/.git}}"
	autogitbundle
' \;
