#!/usr/bin/env -S uv --quiet run --no-project --script --
# https://peps.python.org/pep-0723/
# https://github.com/astral-sh/uv
# /// script
# # Docopt issues SyntaxWarning in Python 3.12
# requires-python = ">=3.11,<3.12"
# dependencies = [
#   "docopt >=0.6.2",
# ]
# ///

"""
Usage:
	{prog}
"""

import sys, locale, os, subprocess, shlex
import docopt


def main(*, args, prog):
	locale.setlocale(locale.LC_ALL, "")

	params = docopt.docopt(
		__doc__.replace("\t", " " * 4).format(prog=os.path.basename(prog)),
		argv=args,
		help=True,
		version=True,
		options_first=False
	)
	assert not params, params

	p = subprocess.run(
		["displayplacer", "list"],
		shell=False,
		check=True,
		capture_output=True,
		encoding="ASCII",
	)
	lines = [l for l in p.stdout.splitlines() if l.startswith("displayplacer \"")]
	assert len(lines) == 1, lines
	displayplacer_args = shlex.split(lines[0])[1:]
	print("\n".join(displayplacer_args))


def smain(argv=None):
	if argv is None:
		argv = sys.argv

	try:
		return main(
			args=argv[1:],
			prog=argv[0]
		)
	except KeyboardInterrupt:
		print(file=sys.stderr)


if __name__ == "__main__":
	sys.exit(smain())
