#!/usr/bin/env python3

import random, argparse, shutil


def main(argv=None):
	opts = _parse_args(argv)

	pins = [genpin(opts.length) for i in range(opts.number)]
	per_line = (opts.width + 1) // (opts.length + 1)

	while pins:
		print(" ".join(pins[:per_line]))
		pins = pins[per_line:]


def genpin(length):
	for i in range(random.randint(1, 5)):
		pin = "".join([str(random.randint(0, 9)) for i in range(length)])
	return pin


def _parse_args(argv=None):
	parser = argparse.ArgumentParser(prog=(argv[0] if argv is not None else None))
	parser.add_argument("--number", "-n", action="store", type=int, metavar="N", default=None, help="how many PINs to generate")
	parser.add_argument("--length", "-l", action="store", type=int, metavar="N", default=6, help="how many digits in each PIN")
	parser.add_argument("--width", "-w", action="store", type=int, metavar="N", default=None, help="print no more than specified chars per line")
	opts = parser.parse_args(argv[1:] if argv is not None else None)

	screen_size = shutil.get_terminal_size()

	if opts.width is None:
		opts.width = opts.length * 10 + 9
		opts.width = screen_size.columns

	if opts.number is None:
		per_line = (opts.width + 1) // (opts.length + 1)
		opts.number = (screen_size.lines - 2) * per_line
		if opts.number % per_line:
			opts.number = opts.number + per_line - opts.number % per_line

	return opts


if __name__ == '__main__':
	main()
