#!/usr/bin/env python3

import argparse, shutil, string, collections


def main(argv=None):
	opts = _parse_args(argv)

	# https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator#Special_designs
	per_line = (opts.width + 1) // (opts.length + 1)
	with open("/dev/random", "rb") as fo:
		passcodes = [genp(fo, opts.length, opts.alphabet) for i in range(opts.number)]
	while passcodes:
		print(" ".join(passcodes[:per_line]))
		passcodes = passcodes[per_line:]


def genp(fo, length, alphabet):
	assert len(alphabet) <= 255
	return "".join(alphabet[x % len(alphabet)] for x in fo.read(length))


def _parse_args(argv=None):
	passcode_type_defaults = collections.namedtuple("passcode_type_defaults", ["alphabet", "length"])
	passcode_types = {
		"pin": passcode_type_defaults(
			alphabet=string.digits,
			length=6,
		),
		"password": passcode_type_defaults(
			alphabet=(string.ascii_lowercase + string.ascii_uppercase + string.digits),
			length=32,
		),
		"punctuation": passcode_type_defaults(
			alphabet=string.punctuation.encode("ascii").translate(None, b"'\"").decode("ascii"),
			length=32,
		),
		"hex": passcode_type_defaults(
			alphabet=(string.digits + string.ascii_uppercase[:6]),
			length=32,
		),
	}
	parser = argparse.ArgumentParser(prog=(argv[0] if argv is not None else None))
	parser.add_argument(
		"--type", "-t",
		dest="type",
		choices=passcode_types.keys(),
		default="password"
	)
	parser.add_argument(
		"--alphabet", "-a",
		dest="alphabet",
		action="store",
		type=str,
		metavar="CHARACTERS",
		default=None
	)
	parser.add_argument(
		"--length", "-l",
		dest="length",
		action="store",
		type=int,
		metavar="N",
		default=None,
		help="how many digits in each PIN"
	)
	parser.add_argument(
		"--width", "-w",
		dest="width",
		action="store",
		type=int,
		metavar="N",
		default=None,
		help="print no more than specified chars per line"
	)
	parser.add_argument(
		"--number", "-n",
		dest="number",
		action="store",
		type=int,
		metavar="N",
		default=None,
		help="how many PINs to generate"
	)

	opts = parser.parse_args(argv[1:] if argv is not None else None)

	if opts.alphabet is None:
		opts.alphabet = passcode_types[opts.type].alphabet

	if opts.length is None:
		opts.length = passcode_types[opts.type].length

	screen_size = shutil.get_terminal_size()

	if opts.width is None:
		opts.width = screen_size.columns

	if opts.width < opts.length:
		parser.error("width can not be less than length")

	if opts.number is None:
		per_line = (opts.width + 1) // (opts.length + 1)
		opts.number = (screen_size.lines - 2) * per_line
		if opts.number % per_line:
			opts.number = opts.number + per_line - opts.number % per_line

	if not opts.alphabet:
		parser.error("alphabet can not be empty")

	return opts


if __name__ == '__main__':
	main()
