#!/usr/bin/env bash

set -o errexit

function main() {
	rev="${1:-"$(git merge-base HEAD "HEAD@{upstream}")"}"
	declare -p rev

	rev=$(git rev-parse "$rev")

	git rev-list --all --not "${rev}^@" --children | grep "^${rev} " | cut -b42- | xargs git lg "^${rev}^@"
}

main "$@"
