#!/usr/bin/env bash


test "$#" -eq 0 && set -- $(git remote)

for remote in "$@"; do
	old_IFS="$IFS"
	IFS=$'\n'
	fetch_specs=(
		$(git config --get-all "remote.$remote.fetch" | sed 's/^+//')
	)
	IFS="$old_IFS"
	unset old_IFS

	local_refs=""
	remote_refs=""

	for spec in "${fetch_specs[@]}"; do
		old_IFS="$IFS"
		IFS=":"
		read remote_glob local_glob < <(echo "$spec")
		IFS="$old_IFS"
		unset old_IFS
		local_refs="${local_refs}"$'\n'"$(
			git rev-parse --symbolic-full-name --glob="$local_glob" | xargs git show-ref | sed "s|${local_glob%\*}|${remote_glob%\*}|g; s/^\([a-fA-F0-9]\{40\}\) /\\1"$'\t/g'
		)"
		remote_refs="${remote_refs}"$'\n'"$(
			git ls-remote "$remote" "$remote_glob"
		)"
	done

	diff -u --label "$remote:local" <(echo "$local_refs") --label "$remote:remote" <(echo "$remote_refs") | colordiff
done
