#!/usr/bin/env bash

set -o errexit

function main() {
	rev="${1:-@}"

	rev=$(git rev-parse "$rev")

	children=(
		$(git rev-list --children --all | sed -n 's/^'$rev' \(.*\)/\1/p')
	)

	show_refs "${children[@]}"
}

function show_refs() {
	refs=()
	for ref in "$@"; do
		refs+=( "$ref~..$ref" )
	done

	git gl --boundary "${refs[@]}"
}

main "$@"
