#!/usr/bin/env python3

import time, sys, subprocess
# pip install pyobjc
from AppKit import NSPasteboard, NSPasteboardTypeString

def get_pasteboard_content() -> str:
	pasteboard = NSPasteboard.generalPasteboard()
	content = pasteboard.stringForType_(NSPasteboardTypeString)
	return content

def main(args: list[str]):
	previous = get_pasteboard_content()

	while True:
		current = get_pasteboard_content()
		if previous == current:
			time.sleep(0.25)
			continue
		previous = current

		if not args:
			print(current)
			continue

		subprocess.run([*args, current], shell=False, check=True)
		print("---")

	return 0


if __name__ == "__main__":
	try:
		sys.exit(main(sys.argv[1:]))
	except KeyboardInterrupt:
		pass
