#!/bin/bash

# TODO Inspect extended attributes (xattr) before deleting files and unneeded folders.

function find() { "/usr/bin/find" "$@"; }
function test() { builtin test "$@"; }

quiet=
folders=()
while test "$#" -gt 0; do
	case "$1" in
		-q|--quiet)
			quiet=1
			shift
			;;
		--)
			shift
			folders+=( "$@" )
			break
			;;
		*)
			folders+=( "$1" )
			shift
			;;
	esac
done

test "${#folders[@]}" -eq 0 && {
	echo "Need folders to delete as arguments."
	exit 1
}

set -o errexit


find_print_operator=()
if [ -z "$RRMDIR_QUIET" ]; then
	find_print_operator=( -print )
fi

for d in "${folders[@]}";
do
	test -d "$d" || {
		echo "Error: '$d' is not a folder."
		continue
	}

	d=$(cd "$d" && pwd) || {
		echo "Error: '$d' is not accessible."
		continue
	}

	test "$(find "$d" -not -type d -not -type f | wc -l)" -ne 0 && {
		echo "Error: I can only handle files and folder. It seems '$d' contains something else."
		continue
	}

	find_garbage_args=(
		-type f
		\(
			-name '.DS_Store'
			-o
			-name 'Thumbs.db'
			-o
			\(
				-name '.localized'
				-empty
			\)
		\)
	)

	test "$(find "$d" -not -type d -not \( "${find_garbage_args[@]}" \) | wc -l)" -ne 0 && {
		if [ -z "$quiet" ]; then
			echo "Error: '$d' is not empty."
		fi
		continue
	}

	# clear the garbage
	find "$d" "${find_garbage_args[@]}" -delete "${find_print_operator[@]}"

	# recursive folder deletion
	find "$d" -mindepth 1 -type d -empty -delete "${find_print_operator[@]}"
	rmdir "$d" || {
		echo "Error: failed to delete '$d'."
		continue
	}
	if [ -z "$RRMDIR_QUIET" ]; then
		echo "$d"
	fi
done
