#!/usr/bin/env python3

"""
Usage:
	{prog} [options] [-i REGEX]... [PATHS...]

Options:
	--jobs, -j NUMBER           Maximum parallel jobs.
	                            [default: 25]
	--playback-rate, -r NUMBER  Calculate duration as if played at specified rate.
	                            [default: 1.0]
	--ffprobe-path PATH         Path to ffprobe executable to be used.
	                            [default: ffprobe]
	--cache-path PATH           Path to file containing cached durations from previous runs.
	--chdir, -C PATH            Change current folder to specified path before doing anything else.
	--ignore, -i REGEX          Exclude paths that match the regex pattern from calculations.
	--date-regex, -d REGEX      Regex pattern for full file name without path to extract date. [default: (?P<date>\\d{{8}}).*]
"""

import sys, locale, asyncio, subprocess, os, collections, re, itertools
# pip install docopt==0.6.2
import docopt


async def main(*, args, prog):
	locale.setlocale(locale.LC_ALL, "")

	params = docopt.docopt(
		__doc__.replace("\t", " " * 4).format(prog=os.path.basename(prog)),
		argv=args,
		help=True,
		version=True,
		options_first=False
	)
	paths = params.pop("PATHS")
	max_parallel_jobs = int(params.pop("--jobs"))
	playback_rate = float(params.pop("--playback-rate"))
	ffprobe_path = params.pop("--ffprobe-path")
	cache_path = params.pop("--cache-path")
	chdir_path = params.pop("--chdir")
	ignored_paths = params.pop("--ignore")
	date_regex = params.pop("--date-regex")
	assert not cache_path, "--cache-path is not implemented"
	assert not params, params

	if chdir_path is not None:
		os.chdir(chdir_path)

	log = asyncio.Queue()
	pending_tasks = []
	printer_task = asyncio.ensure_future(
		printer(queue=log, fo=sys.stdout)
	)

	if not paths:
		paths = ["."]

	pending_durations = asyncio.Queue()

	class PathDuration(object):
		def __init__(self, path):
			self.path = path
			self.duration = 0
			self.count = 0
			self.remaining = 0
			self.unique_days = set()

		def format(self, widths):
			while len(widths) < 2:
				widths.append(0)
			duration = format_seconds(self.duration, speed=playback_rate).lstrip()
			widths[0] = max(widths[0], len(duration))
			avg_daily_increase = ""
			num_unique_days = len(self.unique_days)
			if num_unique_days:
				avg_daily_increase = format_seconds((self.duration * 1.0 / num_unique_days), speed=playback_rate).lstrip()
			widths[1] = max(widths[1], len(avg_daily_increase))
			return f"{duration:>{widths[0]}} [{avg_daily_increase:>{widths[1]}} daily] {self.count:>5n} {format_remaining_count(self.remaining)}{os.path.normpath(self.path)}\n"

	path_durations = collections.OrderedDict()
	files_failed = collections.OrderedDict()

	async def duration_consumer(*, isatty):
		nonlocal path_durations, files_failed
		if isatty:
			await log.put("\n")

		widths = [0, 0]

		while True:
			pfd = await pending_durations.get()
			if pfd is None:
				break

			the_path, the_file, the_duration = pfd
			file_dir = os.path.dirname(the_file)
			file_name = os.path.basename(the_file)
			file_date = None
			if m := re.fullmatch(date_regex, file_name):
				file_date = m.group("date")
			else:
				print("\n\n\n NO MATCH", repr(file_name), end="\n\n\n")
			clear = f"\x1b[{len(path_durations)}F\x1b[0J" if isatty else ""

			if isinstance(the_duration, Exception):
				files_failed[the_file] = the_duration
				path_durations[file_dir].remaining -= 1
			else:
				if file_dir not in path_durations:
					path_durations[file_dir] = PathDuration(file_dir)

				if the_duration == 0:
					path_durations[file_dir].count += 1
					path_durations[file_dir].remaining += 1
				else:
					path_durations[file_dir].remaining -= 1
					path_durations[file_dir].duration += the_duration
					if file_date is not None:
						path_durations[file_dir].unique_days.add(file_date)

				durations = list(path_durations.values())
				durations.sort(key=(lambda pd: (pd.duration, pd.count)))
				if clear:
					await log.put(clear + "".join(pd.format(widths=widths) for pd in durations))

			pending_durations.task_done()

		if not clear:
			# First run will calculate widths
			for pd in durations:
				pd.format(widths=widths)
			# Actual rendering with widths already calculated
			await log.put("".join(pd.format(widths=widths) for pd in durations))

		total = PathDuration("Total")
		total.duration = sum(d.duration for d in path_durations.values())
		total.count = sum(d.count for d in path_durations.values())
		total.unique_days = set(itertools.chain(*(d.unique_days for d in path_durations.values())))
		await log.put("\n" + total.format(widths=widths))

		if files_failed:
			await log.put(f"{files_failed}\n")

	def format_remaining_count(r, *, min_width=3, padding_right=" "):
		return f"{(r):>{min_width}n}{padding_right}" if r else ""

	pending_tasks.append(
		asyncio.ensure_future(duration_consumer(isatty=sys.stdout.isatty()))
	)
	pending_paths = asyncio.Queue()
	pending_tasks.append(
		asyncio.ensure_future(path_consumer(
			queue_in=pending_paths,
			queue_out=pending_durations,
			max_parallel=max_parallel_jobs,
			ffprobe_path=ffprobe_path,
		))
	)
	await walker(paths=paths, queue=pending_paths, ignored_paths=ignored_paths)

	await pending_paths.join()
	await pending_durations.join()

	await asyncio.gather(*pending_tasks)
	#current_task = asyncio.current_task()
	#all_tasks = asyncio.all_tasks()
	#assert {current_task, printer_task} == all_tasks, (current_task, all_tasks)

	await log.put(None)
	await printer_task


async def path_consumer(*, queue_in, queue_out, max_parallel, ffprobe_path):
	async def do_one(p, f):
		try:
			d = await get_video_file_duration(f, ffprobe_path=ffprobe_path)
		except Exception as e:
			d = e
		await queue_out.put((p, f, d))
		queue_in.task_done()


	incoming = []
	pending = set()

	expect_more = True
	while pending or expect_more:
		if expect_more:
			pf = await queue_in.get()
			if pf is not None:
				incoming.append(pf)
				await queue_out.put((*pf, 0))
				await asyncio.sleep(0)
			else:
				queue_in.task_done()
				expect_more = False

		num_to_add = max(0, max_parallel - len(pending))
		if num_to_add:
			pending.update(
				asyncio.ensure_future(do_one(*pf)) for pf in incoming[:num_to_add]
			)
			incoming = incoming[num_to_add:]

		if pending:
			done, pending = await asyncio.wait(pending, return_when=asyncio.FIRST_COMPLETED, timeout=(0 if expect_more else None))

	await queue_out.put(None)


async def walker(*, paths, queue, ignored_paths):
	async for p in walk_paths(*paths, ignored_paths=ignored_paths):
		await queue.put(p)
	await queue.put(None)


DEFAULT_IGNORED_FILES = [
	r"(\._)?\.DS_Store",
	r"(\._)?(favorite|folder)(-atv)?\.(jpg|png)",
	r"Icon\r",
]


DEFAULT_IGNORED_DIRS = [
	r"\.meta",
	r"\.routes",
	r"\.foldericons",
	r"\.playlists",
	r"\.tmp",
]


async def walk_paths(*paths, ignored_files=DEFAULT_IGNORED_FILES, ignored_dirs=DEFAULT_IGNORED_DIRS, ignored_paths=None):
	ignored_files  = re.compile("|".join(f"({x})" for x in ignored_files))
	ignored_dirs   = re.compile("|".join(f"({x})" for x in ignored_dirs))
	ignored_paths  = re.compile("|".join(f"({x})" for x in ignored_paths or []))
	paths = list(paths)

	def output_filter(parent_folder, abs_file_path):
		abs_file_path = os.path.normpath(abs_file_path)
		if ignored_files.fullmatch(os.path.basename(abs_file_path)) is not None:
			return
		if ignored_paths.fullmatch(abs_file_path) is not None:
			return
		yield (parent_folder, abs_file_path)

	while paths:
		p = paths.pop(0)
		if not os.path.isdir(p):
			# yield from is not supporeted in async functions as of Python 3.8.2
			for pf in output_filter(p, p):
				yield pf
		else:
			if ignored_dirs.fullmatch(p) is not None:
				continue
			for rootdir, dirs, files in os.walk(p, topdown=True):
				dirs[:] = [d for d in dirs if ignored_dirs.fullmatch(d) is None]
				for f in files:
					# yield from is not supporeted in async functions as of Python 3.8.2
					for pf in output_filter(p, os.path.join(rootdir, f)):
						yield pf


async def get_video_file_duration(video_file_path, *, ffprobe_path):
	p = await asyncio.create_subprocess_exec(
		ffprobe_path, "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", video_file_path,
		shell=False,
		stdout=subprocess.PIPE,
		stderr=subprocess.PIPE,
	)
	await p.wait()
	assert p.returncode == 0, (p.returncode, (await p.stderr.read()).decode("UTF-8"))
	#TODO:vruyr:bugs How do we know it's UTF-8.
	return float((await p.stdout.read()).decode("UTF-8"))


def format_seconds(seconds, *, subsecond=False, speed=1.0):
	if seconds is None:
		return " " * 12
	seconds = seconds / speed
	assert subsecond == False
	seconds, subseconds = divmod(seconds, 1)
	minutes, seconds = divmod(int(seconds), 60)
	hours, minutes = divmod(minutes, 60)
	result = ""
	if hours:
		result += f"{hours:>4n}h"
	else:
		result += "    "
	if result or minutes:
		if result:
			result += " "
		result += f"{minutes:>2}m"
	if result or seconds:
		if result:
			result += " "
		result += f"{seconds:>2}s"
	return result


async def printer(*, queue, fo):
	while True:
		item = await queue.get()
		if item is None:
			break
		if isinstance(item, (list, tuple)):
			print(*item, file=fo, sep="", end="")
		else:
			print(item, file=fo, sep="", end="")


def smain(argv=None):
	if argv is None:
		argv = sys.argv

	try:
		if sys.platform == "win32":
			asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

		return asyncio.run(
			main(
				args=argv[1:],
				prog=argv[0]
			),
			debug=False,
		)
	except KeyboardInterrupt:
		print(file=sys.stderr)


if __name__ == "__main__":
	sys.exit(smain())
